/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LiquisafeTest } from "./LiquisafeTest";
export type { YourContractTest } from "./YourContractTest";
